# Generated by Django 3.0.6 on 2020-05-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcix_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Movie',
        ),
    ]
